[[redirects]]
  from = "https://dropdown-menu-aleksey-vl-ivanov.netlify.app/*"
  to = "https://dropdown-menu.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dropdown-menu-aleksey-vl-ivanov.netlify.app/*"
  to = "https://dropdown-menu.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dropdown-menu.aleksey-vl-ivanov.com/*"
  to = "https://dropdown-menu.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true